In [2]:
import numpy as np
arr = np.arange(0, 2*3*5)

In [3]:
arr.reshape([2,3,5])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [4]:
 x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
    

In [5]:
np.sum(x, axis=1)

array([[ 2,  4],
       [10, 12]])

In [6]:
np.sum(x, axis=0)

array([[ 4,  6],
       [ 8, 10]])

In [7]:
np.sum(x, axis=2)

array([[ 1,  5],
       [ 9, 13]])

In [13]:
x=np.array([[1,0,0],[0,0,1]])

In [14]:
x.swapaxes(0,1)

array([[1, 0],
       [0, 0],
       [0, 1]])